// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9h6fHmDk2Ja8uu30c6fiovQzqUDpCfXw',
    appId: '1:1098462352279:web:db24bdaa5f72f173ceaad2',
    messagingSenderId: '1098462352279',
    projectId: 'todoi-35c71',
    authDomain: 'todoi-35c71.firebaseapp.com',
    storageBucket: 'todoi-35c71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVg2Z0pxL2TrUcSqGAvmFGIBWuBoBoMk',
    appId: '1:1098462352279:android:61f9a620d7b1596bceaad2',
    messagingSenderId: '1098462352279',
    projectId: 'todoi-35c71',
    storageBucket: 'todoi-35c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9BbUVBFv7Nf4vR8epYYgZce_7ME0ZQ0',
    appId: '1:1098462352279:ios:b57f2789a0cec842ceaad2',
    messagingSenderId: '1098462352279',
    projectId: 'todoi-35c71',
    storageBucket: 'todoi-35c71.firebasestorage.app',
    iosBundleId: 'com.example.tombStone',
  );
}
